### ISSUE TITLE
What's your monthly income?

### ISSUE THREAD

**Issue by pablomaurer** [mhartington/ama#25]
No I would like to know a lot more =) Not sure if I had to open plenty of issues or this is gonna work too? 

# personal
- Where you live?
- How big is the Apartment?
- Do you live together with other people in that Apartment?
- How much does your Apartment cost?
- When you started coding?
- Why you started coding?
- How did you came to ionic?
- How much is your monthly income?
- How much money you have left at the end of the month?
- Are you working 100% at ionic?
- How much you go in the ionic office per week?
- How long is your workday?
- What music do you listen?
- Do you have a wife?
- Do you have kids?
- Do you have a car?
- Are you happy?

# techy
- How do you feel about ionic-1 (ng-1)? 
- How do you feel about ionic-2/3 (ng-2+)?
- How do you feel about ionic-4 (web-components)?

# ionic ama =)
- How does ionic generate an income?
- Does the ionic-premium stuff cover the costs of all employees?

**Comment by mhartington** [comment]
### personal

- Where you live?: Providence, RI
- How big is the Apartment?:  2bed room, nothing fancy
- Do you live together with other people in that Apartment?: My fiancee
- How much does your Apartment cost?: N/A
- When you started coding?: Probably 10ish years ago
- Why you started coding?: High school CS class, but it peaked an interest
- How did you came to ionic?: I was looking for a new mobile framework and found them
- How much is your monthly income?: N/A
- How much money you have left at the end of the month?: N/A
- Are you working 100% at ionic?: Yep!
- How much you go in the ionic office per week?: 0, I work remote
- How long is your workday?: on a decent day, I do a solid 9AM-5PM
- What music do you listen?: Jazz, some lofi hip hop, classical. Anything without words
- Do you have a wife?: Nope, but Im engaged.
- Do you have kids?: Nope
- Do you have a car?: Yep
- Are you happy?: For the most part. I have my days like anyone else


### techy

- How do you feel about ionic-1 (ng-1)?: It was great, but now definitely shows it's age 
- How do you feel about ionic-2/3 (ng-2+)? Great, addresses a lot of issues in V1
- How do you feel about ionic-4 (web-components)? Even better. WC's are the future


### ionic ama

- How does ionic generate an income?: The premium services we offer.
- Does the ionic-premium stuff cover the costs of all employees?: I'd assume so, since I still have a job. I don't really pay attention to the money side of things too much.
