### ISSUE TITLE
How to create real-time messaging with Ionic?

### ISSUE THREAD

**Issue by ihadeed** [mhartington/ama#3]
Hey Mike,

I'm working on a social network app for a client using Ionic for front end, and Node.JS / Express.JS for back end.

I was wondering what is the ideal way to implement real time messaging in the app. I understand Socket.io is good for having a chat room with a lot of people in it. But what I'm trying to do is have 1-on-1 messaging like Facebook Messaging or Google Hangouts.

Do you have any suggestions in mind?

Thanks in advance!

**Comment by mhartington** [comment]
Personally, I a big fan of firebase if I need something to be real time. Simplifies the stack since I don't have to worry about handling the DB and keeping things in sync.

There are a lot of way to do this, all of which use websockets.

https://github.com/realtime-framework/Messaging has some good examples and could help get you in the right direction.
