### ISSUE TITLE
Dotfiles - neovim2 and searching strings

### ISSUE THREAD

**Issue by fragje** [mhartington/ama#9]
Hi and thanks for making a neovim video and sharing your dotfiles. I'm a newbie in vim/tmux but want to give it a spin to see if it's something that could improve my workflow.

I got two questions about your dotfiles:
1. When I open up nvim and try to search for files `<c-p>`, I get this error: `Invalid source name "file_rec/neovim2" is detached`. If I change it to `file_rec/neovim` in init.vim it works, what do I miss?
2. Have you set up a way to search for strings inside files in working directory?

Thanks again for being open and sharing!

**Comment by mhartington** [comment]
Thanks for the kind words! Glad you like them.

1) That was fixed in my local copy, I was just lazy and didn't commit them. Should be fixed now.

2) The best approach I've found so far for searching for strings is using [FZF](https://github.com/junegunn/fzf) and the vim plugin [fzf.vim](https://github.com/junegunn/fzf.vim).
